version: "3.8"
services:
  api:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 5001:5001
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - PORT=5001
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/jsmine?schema=public
    command: yarn run dev
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=rotation-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
